[package]
name = "nbody"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
csv = "1.2.2"
serde = "1.0.180"
serde_derive = "1.0.180"

[profile.release]
opt-level = 3
codegen-units = 1
lto=true
